#!/bin/sh

set -e

lb config noauto \
	--archive-areas "main contrib non-free non-free-firmware" \
	--parent-archive-areas "main contrib non-free non-free-firmware" \
	--firmware-chroot true \
	--firmware-binary true \
	--backports true \
	--debian-installer live \
	--debian-installer-gui false \
	--bootappend-live "boot=live hostname=london components locales=en_GB.UTF-8 keyboard-layouts=us noautologin noroot" \
	--hdd-label points_forces \
	--image-name debian-smars \
	--iso-volume debian-smars \
	--utc-time true \
	--apt-recommends true \
	--iso-preparer "Pierre SMARS smars@yuntech.edu.tw" \
	--clean \
	"${@}"
