#!/bin/sh

set -e

lb config noauto \
	--archive-areas "main contrib non-free" \
	--parent-archive-areas "main contrib non-free" \
	--firmware-chroot true \
	--firmware-binary true \
	--backports true \
	--debian-installer none \
	--debian-installer-gui false \
	--bootappend-live "boot=live hostname=manchester components locales=en_GB.UTF-8 keyboard-layouts=us noautologin noroot" \
	--hdd-label points_forces \
	--image-name debian-smars-s \
	--iso-volume debian-smars-s \
	--utc-time true \
	--apt-recommends true \
	--iso-preparer "Pierre SMARS smars@yuntech.edu.tw" \
	--clean \
	"${@}"
